# Only run against master
trigger:
  - master

# Don't run against PRs
pr: none

variables:
  AppServicePlan_Name: minecraft-tekkit
  Authentication_PasswordOrKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfC6dr0YY6shVTkJgZKkDo2ww/2DlT8LXXEwU6m7WLiFMo/WlwgOi2bRpwvetC1nwOVGVPACCyII+uUuZ/vYHh7RCCAZ4xaZtUEQgu34lRhfOAnG5hCVKdpFAQ0danBCv54XYTq+Edkxw29H3pQrgh0id7+z2p59+iCYYHXWddt7PhpedTW6qVf0my6DIB5GPKRNlooXN9jYjVjDtceGYtxNs/TjsQONrx60YYoJzmvQUAbbtb7ubeB4LDnKmr1a/w7Wf5ECQDFcsAkTbPg+DLyytRJqCgoL7V83SRrqnuhXiHFHZ6bXDGZTA2HKiCmWX5B9A9nb5isxNjcpxa6hXv81uBL49BIIiTABpZF5eptxwAW0eWqZ0j313OFJYk2fgWJig26xcP94DWX3x/AbJRxLwVjxCJ8nu6BNC+FM4mgdCA6RKQffPMlssSeSWxln9QvaNA0cXKcoN969GMDuhG9TppSUAPTKeU79OAuSEzx/bbSO7kxeX2xMiEbOBx1BJBFlFYAup22WHSQvlXhaS/jqZ8F6YUd6LwlB/n4kjD6TCE++Ty12KP8kTHTecCZhYh4fC20igJA80vhk0vPvgmrEmOU20DGGnEMJziJvRsyB9waN5AUp0vZdcgXwuH2f0SOMIhA1Guya549Hy0nkCyEcExpTrtjhV+XG1RFR3FzQ== contact@sethreid.co.nz
  Authentication_UserName: minecraft-admin
  AzureSubscription: Microsoft Azure Sponsorship (15253eaa-8a37-4163-8903-aa688499a16f)
  ResourceGroup_Location: 'Australia East'
  ResourceGroup_Name: minecraft-tekkit
  WebApp_BuildConfiguration: Release
  WebApp_OutputFolder: $(Build.ArtifactStagingDirectory)/WebApp
  WebApp_ProjectDirectory: $(Build.SourcesDirectory)/src/$(WebApp_ProjectName)
  WebApp_ProjectFile: $(WebApp_ProjectDirectory)/$(WebApp_ProjectName).csproj
  WebApp_ProjectName: MinecraftServer.Web
  WebApp_SiteName: minecraft-tekkit
  VirtualMachine_Name: minecraft-tekkit
  VirtualMachine_DnsName: minecraft-tekkit

stages:
  # Download and build the project
  - stage: Build
    displayName: Build
    jobs:
      - job: run_build
        pool:
          vmImage: "windows-latest"
        steps:

          ## Run the dotnet build/publish
          - script: |
              dotnet publish $(WebApp_ProjectFile) --configuration $(WebApp_BuildConfiguration) --output $(WebApp_OutputFolder)
            displayName: Publish dotnet web app

          - task: CopyFiles@2
            displayName: Copy ARM template
            inputs:
              contents: $(Build.SourcesDirectory)/azure-deploy.json
              targetFolder: $(Build.ArtifactStagingDirectory)

          ## Archive the files into a zip file for publishing
          - task: ArchiveFiles@2
            displayName: Zip build artifacts
            inputs:
              rootFolderOrFile: $(WebApp_OutputFolder)
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/Web.zip"
              includeRootFolder: false

          ## Publish the zip file
          - task: PublishBuildArtifacts@1
            displayName: Publish build artifacts
            inputs:
              pathtoPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: drop

  # Deploy the resources
  - stage: DeployResourceGroup
    displayName: Deploy Resource Group
    dependsOn: Build
    jobs:
    - deployment: Arm
      displayName: Deploy Resource Group
      pool:
        vmImage: 'windows-latest'
      environment: 'production'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: drop
            - task: AzureResourceGroupDeployment@2
              displayName: 'ARM deployment'
              inputs:
                azureSubscription: '$(AzureSubscription)'
                resourceGroupName: $(ResourceGroup_Name)
                location: $(ResourceGroup_Location)
                csmFile: $(Pipeline.Workspace)/drop/azure-deploy.json
                deploymentMode: 'Incremental'
                overrideParameters: >-
                  -adminPasswordOrKey "$(Authentication_PasswordOrKey)"
                  -adminUsername "$(Authentication_UserName)"
                  -appServiceName "$(WebApp_SiteName)"
                  -appServicePlanName "$(AppServicePlan_Name)"
                  -dnsNameForPublicIP "$(VirtualMachine_DnsName)"

  # Deploy the resources and application
  - stage: Production
    dependsOn:
    - Build
    - DeployResourceGroup
    displayName: Production
      jobs:
      - deployment: Production
        displayName: Deploy Resource Group
        pool:
          vmImage: 'windows-latest'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                artifact: drop
              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy web app'
                inputs:
                  azureSubscription: 'Microsoft Azure Sponsorship (15253eaa-8a37-4163-8903-aa688499a16f)'
                  WebAppName: $(WebApp_SiteName)
                  packageForLinux: '$(Pipeline.Workspace)/drop/Web.zip'
